version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.12 # 필요에 따라 변경`
    commands:
      - apt-get update -y
      - apt-get install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform --version
      - terraform init
  build:
    commands:
      - terraform apply -auto-approve 
  post_build:
    commands:
      - terraform destroy -auto-approve
      - echo "Build completed on `date`"
