version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform --version
      - terraform init
  build:
    commands:
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Build completed on `date`"
